### ISSUE TITLE
Can't see text in console as top banner is blocked

### ISSUE THREAD

**Issue by Relishablez** [pythonanywhere/help_pages#115]
Greetings! 

On the console, the surrounding banner blocks the text entered and the console seemingly overlaps text so I can't make out what I am typing or any errors or such thrown back, see screenshot:

[https://i.imgur.com/KiaoDSP.png](url)

**Comment by gpjt** [comment]
Hi there -- these issues are for reporting problems with our help pages; if you have a tech support request regarding PythonAnywhere, please email us at support@pythonanywhere.com.
