### ISSUE TITLE
A preconfigured FastAPI with  Unicron package is Needed in order to run FastsAPI webapp with Unicorn package

### ISSUE THREAD

**Issue by 4imranchaudhry** [pythonanywhere/help_pages#120]
I tried to install and use FastAPI with unicron package using all possible ways to install and use Unicorn package, it does install but wont run Unicorn, and fails with error. As various environments with » Django » web2py » Flask » Bottle are available. FastAPI is the most advanced and popular framework for Python web async development.

**Comment by gpjt** [comment]
Hi there -- this is the repository for our help pages, where you can suggest updates to them.  If you have a PythonAnywhere-related question or suggestion, you can drop us a line at support@pythonanywhere.com
