### ISSUE TITLE
Add filess.io to Whitelist IPs

### ISSUE THREAD

**Issue by mahi-official** [pythonanywhere/help_pages#123]
I am trying to access the Relational DB from PythonAnywhere Application but it does not allow me to connect to the database.
I get the error: **_connection to server at "vmd.h.filess.io" (161.97.121.243), port 5433 failed: Connection refused_** 

After researching a lot, I found that the website/server is not listed in the Allowlisted sites for free users and because of that, I cannot connect to the DB.

Please add **vmd.h.filess.io** to the allowed hosts list.

**Comment by gpjt** [comment]
These are the issues for our help pages specifically; you can contact PythonAnywhere tech support at support@pythonanywhere.com.
