### ISSUE TITLE
Scheduled task window 

### ISSUE THREAD

**Issue by kick707** [pythonanywhere/help_pages#129]
Scheduled tasks window supports only hourly or daily , can you please add support for ore granular scheduler, for example run every X (which is an integer) , and type [minutes,hours,days,weekdays [Su,Mo, Tu, We, Th, Fr, Sa],weeks,months,years] ?

**Comment by gpjt** [comment]
This is the repository for the PythonAnywhere help pages; if you would like support on PythonAnywhere itself, please email us at support@pythonanywhere.com.
