### ISSUE TITLE
Clarification for https://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs/

### ISSUE THREAD

**Issue by alphaCTzo7G** [pythonanywhere/help_pages#24]
I saw that you are using the `workon` command in here.

Are you assuming that `virtualenvwrapper` is installed along with `virtualenv`?

Perhaps that could be clarified in there..

**Comment by pythonanywhere** [comment]
Virtualenvwrapper is installed on PythonAnywhere by default, so I think it'll always work,
