### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RDIL** [pythonanywhere/help_pages#46]
@gpjt just noticed that the link below this header is broken:
https://github.com/pythonanywhere/help_pages/blob/master/articles/403ForbiddenError.md#requesting-an-addition-to-the-whitelist
may want to fix it while your at it :)

**Comment by gpjt** [comment]
Hmm, it looks like it's OK on the live help site at https://help.pythonanywhere.com/pages/403ForbiddenError ...?

**Comment by RDIL** [comment]
Oh right, forgot links aren't made relative on GH
