### ISSUE TITLE
Have an article on the differences between bcrypt and py-bcrypt

### ISSUE THREAD

**Issue by ReckoningReckoner** [pythonanywhere/help_pages#6]
This was a big that took me HOURS to figure out. I think it would be useful to add an article in the help pages about the following:

I was creating a flask app, and I was using [bcrypt](https://pypi.python.org/pypi/bcrypt/2.0.0) to validate my users passwords. My code worked on my local machine fine, passed all my unit tests, yada-yada. I pulled my code onto Python Anywhere, and opened a python3 shell and did this:

```
$ python3
>>> import bcrypt
>>> 
```

Everything worked, so I guess that PA has it preinstalled. Let me now run my unit tests:

`TypeError: Unicode-objects must be encoded before hashing`

Hm, probably a Python 2 vs 3unicode thing. No worries, I'll just install the Python 3 version of bcrypt.

`pip3 install --user bcrypt`

Then, I run my unit tests again. Everything passes, looking good. However, I try going on my website, but all I get now is a 500 error with this in my error log:

`ValueError: Invalid salt`

After spending a VERY long time messing around with utf encodings, strings and even Flask-bcrypt (not python 3 friendly), I still couldn't figure anything out. Turns out, if you do a pip freeze, PA has [py-bcrypt](https://pypi.python.org/pypi/py-bcrypt/) preinstalled, instead of bcrypt. 

The really frustrating part is that **the module to use py-bcryt is actually called bcrypt!** This explains why my unit tests worked, as they were using the _bcrypt module_, whereas the WSGI was probably using the _py-bcrypt_ module. After hours of googling and debugging... Finally! A solution!

So, here's what to do if you're using bcrypt in your program and you're going to host your code on Python Anywhere:

1. Use virtualenvs
2. Refactor your code so that it works with py-bcrypt. Here are the major differences I could find (bcrypt vs py-bcryt)
    - In bcrypt, you will need to encode the hash and string into bytes if you wanna use the hashpw method (assuming you're storing your hash as string in your DB). 
    ```
    >>> hash.encode('utf-8') == bcrypt.hashpw(b"badpassword", hash.encode('utf-8'))
    >>> True
    ```
    In py-bcrypt you must only use strings:
    ```
    >>> hash = bcrypt.hashpw("badpassword", bcrypt.gensalt())
    >>> hash == bcrypt.hashpw("badpassword", hash)
    >>> True
    ```
    - Hashes generated with bcrypt will NOT be compatible with the hashes used with py-bcrypt. Forgive me if I get this incorrect, but bcrypt hashes begin with the `$2b$`, whereas py-bcrypt hashes start with `$2a`. You will need to change your hashes in order for the program to work, though I'm not entirely sure if simply changing the prefix will make your hashes compatible.

BTW I posted a bunch of extra details for the lone Googler who also has this obscure problem.

**Comment by hjwp** [comment]
that does sound like a very baffling issue!  congrats on getting to the bottom of it.  am not sure we'll do a specific help page for it, but i'll do at least a post in the forums and link to this discussion.

out of interest, do you think that, if you'd just been using a virtualenv all along, you could have just used "bcrypt" intead of py-bcrypt, all the way through?

**Comment by Cheaterman** [comment]
This is insane. I bumped into it today. Thanks for all the hard work.
