### ISSUE TITLE
Mismatched version references in Save&Run/hashbang help article

### ISSUE THREAD

**Issue by therden** [pythonanywhere/help_pages#62]
On your site's help page [How can I use a different version of Python for the Save & Run button?](https://help.pythonanywhere.com/pages/SaveAndRunPythonVersion), the Python versions which references both within the text (3.7 and 3.6) and also within the second code example (3.4 and 3.3) appear to have drifted apart over time.

**Comment by therden** [comment]
As encouraged at the bottom of the the article page referenced above, I tried to contribute improvements to this article, but have been thwarted.

I cloned the **help_pages** repository, created a new branch for this issue, updated the Markdown file, and committed it to my local repo.  

But when tried to create a *Pull Request* from within GitHub, I was blocked from doing so, and was likewise unable to push my branch from my local repository to the GitHub-hosted one.

**Comment by millenniumhand** [comment]
I have updated the help page. Since the prints in the code examples are there mostly as comments, I have not used the code that you provided to print the version that is running, since that obscures what the shebang is doing.

**Comment by therden** [comment]
I understand.

You overlooked the need to update the reference from 3.6 to 3.7.

**Comment by millenniumhand** [comment]
Thanks. I have fixed that.
