### ISSUE TITLE
Please update documentation error on mysql python code snippet (Connect From Outside)

### ISSUE THREAD

**Issue by antnun** [pythonanywhere/help_pages#80]
Change the mysql import with **pymysql** on the following article 

[https://help.pythonanywhere.com/pages/AccessingMySQLFromOutsidePythonAnywhere](url)

Section _From Python code_

Some users (me included)  have been experiencing errors DB frozen errors while trying access the DB via SSH Tunnel using that code. 

Articles with Examples on this Topic 
- https://www.pythonanywhere.com/forums/topic/13918/#id_post_93657
- https://www.pythonanywhere.com/forums/topic/29660/#id_post_93653 (Mine)

My working example after changing that:
```
import pymysql as sqlConnector
import sshtunnel

sshtunnel.SSH_TIMEOUT = 5.0
sshtunnel.TUNNEL_TIMEOUT = 5.0


dbHostName='zzzzzz.mysql.pythonanywhere-services.com'
dbName='myDB$tendlc_db'
dbUserName='myDBuser'
dbUserPassword='xxxxxx!'
sshHostName='ssh.pythonanywhere.com'
pyUserName='myLogin'
pyPassWord='myPWD'

#Perform Connection test and Sample Query
def dbtest(): 
    dbapi_config.refresh()
    with sshtunnel.SSHTunnelForwarder(
        (sshHostName),
        ssh_username=pyUserName, ssh_password=pyPassWord,
        remote_bind_address=(dbHostName, 3306)
    ) as tunnel:
        print ("SSH TUNNEL ESTABLISHED")
        connection = sqlConnector.connect(
            user=dbUserName, password=dbUserPassword,
            host='127.0.0.1', port=tunnel.local_bind_port,
            database=dbName,
        )
        print("CONNECTED")
        tst_query="SHOW TABLES"
        execute_query(conn=connection,query=tst_query)
        connection.close()

#This Helper function o execute query I am not the author but someone else's I cant find on my files
def execute_query(conn, query):
    cur = conn.cursor()
    cur.execute(query)
    print(cur.description)
    print()
    for row in cur:
        print(row)

```

**Comment by antnun** [comment]
BTW: if you share some tips on how to propose the fix via hit (not that skilled, on it) happy to do so.

**Comment by gpjt** [comment]
I'm not sure that pymysql is the right solution in the general case -- the package I'd normally recommend is [`mysqlclient`](https://pypi.org/project/mysqlclient/).  I've updated the page to use that one (and to include some installation instructions for it).
