### ISSUE TITLE
Not able to rename the web app

### ISSUE THREAD

**Issue by hemansah** [pythonanywhere/help_pages#81]
Hi there, 
I was trying to give custom domain to my deployed application. So I was looking in the help pages - [this](https://help.pythonanywhere.com/pages/UsingANewDomainForExistingWebApp) shows that I can click on the pencil to set my domain, but in my case it is not coming or it is removed.

**Comment by gpjt** [comment]
Do you have a paid account?  That option is not available to free ones.
