### ISSUE TITLE
Add AstraDB to the whitelist

### ISSUE THREAD

**Issue by bitsnaps** [pythonanywhere/help_pages#84]
Hello,

Can you add AstraDB to the whitelist api? it's usually used to store document and query data from cassandra DB using a REST api, the url is something like: 
```http://$ASTRA_CLUSTER_ID-$ASTRA_REGION.apps.astra.datastax.com/api
```
More about AstraDB at: https://docs.datastax.com/en/astra/docs/retrieving-rows-from-your-table.html

**Comment by gpjt** [comment]
If you'd like to request an addition to the whitelist, please send us a message as per the [help page](https://help.pythonanywhere.com/pages/RequestingWhitelistAdditions/).
